### PR TITLE
Script to delete openstack resources only using cluster id

### PR DESCRIPTION
**Pull request by adduarte**
The script will delete openstack resources associated
with the infra-id provided on the OS_CLOUD specified.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Did you check out “destroy_cluster.sh -f”? It should do something very similar if I’m not mistaken.
Do you think we could merge the two scripts?

**Comment by adduarte** [comment]
> Did you check out “destroy_cluster.sh -f”? It should do something very similar if I’m not mistaken.
> Do you think we could merge the two scripts?

Perhaps. "destroy_cluster.sh" requires the existance of "clusters/${cluster_name}" directory.
this scrip is  meant for when there is no cluster directory avaialbe. Basically a script to delete zombie clsuters on a ci system. 
but we might be able to merge them yes.

**Comment by pierreprinetti** [comment]
Right. It's weird though that the script requires a file it doesn't use :/ Maybe we can fix that?

**Comment by mandre** [comment]
> > Did you check out “destroy_cluster.sh -f”? It should do something very similar if I’m not mistaken.
> > Do you think we could merge the two scripts?
> 
> Perhaps. "destroy_cluster.sh" requires the existance of "clusters/${cluster_name}" directory. this scrip is meant for when there is no cluster directory avaialbe. Basically a script to delete zombie clsuters on a ci system. but we might be able to merge them yes.

It does not require anything to exist, `destroy_cluster.sh` will happily take infra-id as a parameter:
```
destroy_cluster.sh -i <my-infra-id>
```

By default it will use the installer to destroy the cluster, but you can also have it use openstack commands directly by passing the `-f | --force` flag. So by passing both the `-i` and `-f` flag, you'll get the exact same behavior as the script you're adding here.
I'm thus closing this PR. Feel free to open a new PR to add things you think are missing from `destroy_cluster.sh`.

**Pull request closed without merging**
