### PR TITLE
Move cluster configs in a sub-directory

### PR DESCRIPTION
**Pull request by mandre**
Again, this is to stop polluting the root of the repository with user
config files.

Also removes the executable fit from example config files as it is not needed.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
I am not sure I understand this change.

I only ever use one `cluster_config.sh`, with a `case $OS_CLOUD` that selects the flavors for the platform. In my case, having one file or one file in one `config/` directory is not a big deal.

If instead you use multiple config files, you currently have to pass an environment variable for choosing it.
In essence, you can already pass a directory:
`CONFIG=./config/cluster_config.sh "${shiftstack_path}/run_ocp"`

What case does this change cover?

**Comment by mandre** [comment]
Hmm, you're right. Perhaps we could improve the `cluster_config.sh.example` file to add a switch on `$OS_CLOUD` like you did.

**Comment by pierreprinetti** [comment]
This is what I have:

```
case $OS_CLOUD in
	moc)
		export OS_CLOUD
		export OPENSTACK_REGION='moc-kzn'
		export OPENSTACK_FLAVOR='m1.s2.xlarge'
		export OPENSTACK_WORKER_FLAVOR='m1.s2.large'
		export OPENSTACK_EXTERNAL_NETWORK='external'
		;;
	psi)
		export OS_CLOUD
		export OPENSTACK_REGION='regionOne'
		export OPENSTACK_FLAVOR='ocp.min.master'
		export OPENSTACK_WORKER_FLAVOR='ocp.min.worker'
		export OPENSTACK_EXTERNAL_NETWORK='provider_net_shared_3'
		;;
	psi-pub)
		export OS_CLOUD
		export OPENSTACK_REGION='regionOne'
		export OPENSTACK_FLAVOR='s.xl'
		export OPENSTACK_WORKER_FLAVOR='ci.s.l'
		export OPENSTACK_EXTERNAL_NETWORK='internet'
		;;
	*)
		>&2 echo "Unknown cloud '${OS_CLOUD}'"
		exit 1
		;;
esac
```

**Comment by mandre** [comment]
Replaced by #84

**Pull request closed without merging**
