### PR TITLE
Change license from GPL to Apache2

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by mandre** [comment]
I don't have problems relicensing from GPL3 to the more permissive Apache2 but this should be discussed with [everyone who contributed code to this repo](https://github.com/shiftstack/shiftstack-ci/graphs/contributors).

**Comment by pierreprinetti** [comment]
@Fedosin @EmilienM @iamemilio @mdbooth @adduarte @maxwelldb 

Would you be OK relicensing your work to the Apache2 license, for consistency with the rest of the [OpenStack](https://governance.openstack.org/tc/reference/licensing.html) and [OpenShift](https://github.com/openshift/kubernetes/blob/master/LICENSE) software?

**Comment by maxwelldb** [comment]
No problem for me.

**Comment by EmilienM** [comment]
:+1:

**Comment by pierreprinetti** [comment]
/close

I did not manage to get the required approvals.

**Comment by Fedosin** [comment]
I don't mind actually :)

**Pull request closed without merging**
